#!/usr/bin/python

# Import modules for CGI handling
import cgi, json

software_version = open("/etc/openwrt_release").read().split('\n')[1].split("\"")[1]

result = {
	"result": {
	  "softwareVersion"               : software_version,
	  "ispDownloadSpeed"              : "12.8",
	  "ispUploadSpeed"                : "3.6",
	  "softwareVersionUpdateDate"     : "16/06/2014",
	  "lastCheckedDate"               : "18/06/2014",
	  "routerBand"                    : "5",
	  "routerChannel"                 : "custom",
	  "routerCustomChannel"           : "??",
	  "routerChannelBandwidth"        : "20",
	  "routerVpnConfiguration"        : "None",
	  "openwirelessBandwidth"         : "5",
	  "openwirelessData"              : "30",
	  "openwirelessBand"              : "2.4",
	  "openwirelessChannel"           : "auto",
	  "openwirelessCustomChannel"     : "??",
	  "openwirelessChannelBandwidth"  : "20",
	  "openwirelessVpnConfiguration"  : "None",
	  "wanIp" : "192.168.1.4",
	  "lanIp" : "184.251.4.14"
	}
}

print "Content-Type:application/json\r\n"
print json.JSONEncoder().encode(result)
